-- Catálogo da Sara Cosméticos: Postgres, RLS e Storage.
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists public.produtos (
  id bigint generated by default as identity primary key,
  codigo text not null unique check (char_length(codigo) between 1 and 60),
  nome text not null check (char_length(nome) between 2 and 160),
  marca text not null default 'Sara Cosméticos' check (char_length(marca) between 1 and 100),
  categoria text not null check (categoria in ('perfumaria', 'maquiagem', 'skincare', 'corpo', 'cabelos', 'kits', 'outros')),
  preco numeric(10, 2) check (preco is null or (preco >= 0 and preco <= 999999.99)),
  preco_promocional numeric(10, 2) check (
    preco_promocional is null
    or (preco is not null and preco_promocional >= 0 and preco_promocional < preco)
  ),
  preco_a_partir_de boolean not null default false check (not preco_a_partir_de or preco is not null),
  quantidade_estoque integer not null default 0 check (quantidade_estoque between 0 and 999999),
  descricao text check (descricao is null or char_length(descricao) <= 1200),
  imagem_path text check (
    imagem_path is null
    or (char_length(imagem_path) <= 500 and imagem_path !~ '(^|/)\.\.(/|$)')
  ),
  ativo boolean not null default true,
  destaque boolean not null default false,
  ordem integer not null default 0 check (ordem between 0 and 999999),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index if not exists produtos_catalogo_ordem_idx
  on public.produtos (destaque desc, ordem, nome)
  where ativo = true;
create index if not exists produtos_categoria_ativos_idx
  on public.produtos (categoria, ordem, nome)
  where ativo = true;

create or replace function private.set_atualizado_em()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$;

revoke all on function private.set_atualizado_em() from public, anon, authenticated;

drop trigger if exists produtos_set_atualizado_em on public.produtos;
create trigger produtos_set_atualizado_em
before update on public.produtos
for each row execute function private.set_atualizado_em();

alter table public.produtos enable row level security;
alter table public.produtos force row level security;

revoke all on table public.produtos from anon, authenticated;
grant select on table public.produtos to anon;
grant select, insert, update, delete on table public.produtos to authenticated;
grant usage, select on sequence public.produtos_id_seq to authenticated;

create policy "catalogo publico le produtos ativos"
on public.produtos for select
to anon, authenticated
using (ativo = true);

create policy "administrador le todos os produtos"
on public.produtos for select
to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "administrador cadastra produtos"
on public.produtos for insert
to authenticated
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "administrador atualiza produtos"
on public.produtos for update
to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "administrador remove produtos"
on public.produtos for delete
to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'product-images',
  'product-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "administrador lista imagens de produtos"
on storage.objects for select
to authenticated
using (
  bucket_id = 'product-images'
  and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

create policy "administrador envia imagens de produtos"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'product-images'
  and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

create policy "administrador atualiza imagens de produtos"
on storage.objects for update
to authenticated
using (
  bucket_id = 'product-images'
  and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
)
with check (
  bucket_id = 'product-images'
  and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

create policy "administrador exclui imagens de produtos"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'product-images'
  and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);
